version: "3.6"
services:
  autonod:
    container_name: autonod
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    image: ${IMAGE_APP_NAME}:1.0
    volumes:
      - ../app:/usr/src/app:ro
      - ../data/database:/database
    environment:
      - PYTHONUNBUFFERED=1
    command: python app.py
    restart: always
